version : '3'
services:
  api-petitbag:
    container_name: app-petitbag
    image: app
    build:
      context: app
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:app-petitbag.paraanime.com
      - traefik.port=3006
      - traefik.docker.network=traefik-ok_default
      - traefik.frontend.protocol=http
      - traefik.frontend.entryPoints=http,https
    networks:
      - traefik-ok_default
networks:
  traefik-ok_default:
    external: true
